export const menuCategories = [
  { id: 'new', name: 'Novità!', icon: '⭐' },
  { id: 'coupons', name: 'Salvaeuro', icon: '🏷️', iconSrc: '/brand/categories/salvaeuro-icon.png' },
  {
    id: 'meals',
    name: 'Menu',
    icon: '🍔🍟🥤',
    iconSrc: '/brand/categories/menu-icon.png',
    isSelected: true,
  },
  {
    id: 'happyMeals',
    name: 'Happy Meal',
    icon: '😊',
    iconSrc: '/brand/categories/happy-meal-icon.png',
  },
  { id: 'burgers', name: 'Burgers', icon: '🍔', iconSrc: '/brand/categories/burger-icon.png' },
  { id: 'salads', name: 'Salads', icon: '🥗', iconSrc: '/brand/categories/salad-icon.png' },
  { id: 'sides', name: 'Sfiziosità', icon: '🍟', iconSrc: '/brand/categories/sfiziosita-icon.png' },
  { id: 'sweets', name: 'Gelati & Milkshake', icon: '🍦', iconSrc: '/brand/categories/dessert-icon.png' },
  {
    id: 'mcCafe',
    name: 'McCaffè & Desserts',
    icon: '☕',
    iconSrc: '/products/mccafe/caffe-espresso.png',
  },
  { id: 'drinks', name: 'Drinks', icon: '🥤', iconSrc: '/brand/categories/bevande-icon.png' },
];

export const topPills = ['All', 'Beef', 'Chicken', 'McCrispy', 'McFlurry', 'Plant Based'];

/** Filtri pill per categoria (pill = id UI, tag = filtro su products.tags). */
export const categoryPillConfig = {
  salads: [
    { pill: 'All' },
    { pill: 'SaladChicken', tag: 'chicken', labelKey: 'pillSaladChicken' },
    { pill: 'SaladVegetarian', tag: 'vegetarian', labelKey: 'pillSaladVegetarian' },
    { pill: 'SaladMenu', tag: 'menu', labelKey: 'pillSaladMenu' },
  ],
  drinks: [
    { pill: 'All' },
    { pill: 'DrinkSoft', tag: 'soft', labelKey: 'pillDrinkSoft' },
    { pill: 'DrinkWater', tag: 'water', labelKey: 'pillDrinkWater' },
    { pill: 'DrinkJuice', tag: 'juice', labelKey: 'pillDrinkJuice' },
    { pill: 'DrinkTea', tag: 'tea', labelKey: 'pillDrinkTea' },
  ],
  happyMeals: [
    { pill: 'All' },
    { pill: 'HappyChicken', tag: 'chicken', labelKey: 'pillHappyChicken' },
    { pill: 'HappyBeef', tag: 'beef', labelKey: 'pillHappyBeef' },
    { pill: 'HappyNuggets', tag: 'nuggets', labelKey: 'pillHappyNuggets' },
  ],
  sides: [
    { pill: 'All' },
    { pill: 'SideFries', tag: 'fries', labelKey: 'pillSideFries' },
    { pill: 'SideNuggets', tag: 'nuggets', labelKey: 'pillSideNuggets' },
    { pill: 'SideLoaded', tag: 'loaded', labelKey: 'pillSideLoaded' },
    { pill: 'SideSauces', tag: 'sauce', labelKey: 'pillSideSauces' },
    { pill: 'SideSpecial', tag: 'special', labelKey: 'pillSideSpecial' },
  ],
  sweets: [
    { pill: 'All' },
    { pill: 'SweetMilkshake', tag: 'milkshake', labelKey: 'pillSweetMilkshake' },
    { pill: 'SweetMcFlurry', tag: 'mcflurry', labelKey: 'pillSweetMcFlurry' },
    { pill: 'SweetSundae', tag: 'sundae', labelKey: 'pillSweetSundae' },
    { pill: 'SweetGelato', tag: 'gelato', labelKey: 'pillSweetGelato' },
  ],
};

/** Sottocategorie McCaffè & Desserts (navigazione a due livelli). */
export const mcCafeSubcategories = [
  { id: 'hotCoffee', labelKey: 'mcCafeSubHotCoffee' },
  { id: 'croissant', labelKey: 'mcCafeSubCroissant' },
  { id: 'cake', labelKey: 'mcCafeSubCake' },
  { id: 'donut', labelKey: 'mcCafeSubDonut' },
  { id: 'muffin', labelKey: 'mcCafeSubMuffin' },
  { id: 'macaron', labelKey: 'mcCafeSubMacaron' },
  { id: 'fresh', labelKey: 'mcCafeSubFresh' },
  { id: 'juice', labelKey: 'mcCafeSubJuice' },
  { id: 'mcCafeMenu', labelKey: 'mcCafeSubMenu' },
  { id: 'mcpops', labelKey: 'mcCafeSubMcPops' },
];

export function getMcCafeSubcategoryLabel(subId, language, t) {
  const sub = mcCafeSubcategories.find((s) => s.id === subId);
  return sub ? t(language, sub.labelKey) : subId;
}

export function filterMcCafeBySubcategory(products, subcategoryId) {
  return products.filter(
    (p) => p.category === 'mcCafe' && p.subcategory === subcategoryId
  );
}

export function countMcCafeBySubcategory(products, subcategoryId) {
  return filterMcCafeBySubcategory(products, subcategoryId).length;
}

/** Foto di copertina per card sottocategoria (bestseller > nuovo > primo prodotto). */
export function getMcCafeSubcategoryCoverImage(products, subcategoryId) {
  const items = filterMcCafeBySubcategory(products, subcategoryId);
  if (!items.length) return null;
  const pick =
    items.find((p) => p.isBestseller && p.image) ??
    items.find((p) => p.isNew && p.image) ??
    items.find((p) => p.image);
  return pick?.image ?? null;
}

/** Bibita di default nei menu combo e modali. */
export const defaultMealDrinkImage = '/products/drinks/coca-cola.png';

/** Patatine di default nei menu combo e modali. */
export const defaultMealFriesImage = '/products/sides/patatine-medie.png';

export function getCategoryPills(categoryId) {
  return categoryPillConfig[categoryId]?.map((c) => c.pill) ?? topPills;
}

export function getCategoryPillMeta(categoryId) {
  return categoryPillConfig[categoryId] ?? null;
}

/** Percorsi icone ingredienti (personalizzazione panini / insalate). */
export const extraIngredientImages = {
  cheese: '/products/extras/formaggio.png',
  bacon: '/products/extras/bacon.png',
  tomato: '/products/extras/pomodoro.png',
  onion: '/products/extras/cipolla.png',
  onionCrispy: '/products/extras/cipolla-croccante.png',
  pickles: '/products/extras/cetriolini.png',
  lettuce: '/products/extras/lattuga.png',
  salad: '/products/extras/insalata.png',
  sauceBigMac: '/products/extras/salsa-big-mac.png',
  sauceBigArch: '/products/extras/salsa-big-arch.png',
  sauceCrispy: '/products/extras/salsa-crispy.png',
  sauceCrispySpicy: '/products/extras/salsa-crispy-spicy.png',
  sauceCaesar: '/products/extras/salsa-caesar.png',
  sauceTartara: '/products/extras/salsa-tartara.png',
  sauceYogurt: '/products/extras/salsa-yogurt.png',
  sauceSweetOnionBaconJam: '/products/extras/salsa-sweet-onion-bacon-jam.png',
  beef: '/products/extras/carne-bovina.png',
  chickenBreaded: '/products/extras/pollo-impanato.png',
  chickenFillet: '/products/extras/filetto-pollo.png',
  fish: '/products/extras/merluzzo-impanato.png',
  ham: '/products/extras/prosciutto-cotto.png',
  bun: '/products/extras/pane.png',
  bunMcCrunchy: '/products/extras/pane-mccrunchy.png',
  tortilla: '/products/extras/tortilla.png',
};

const saladExtraProfiles = {
  saladGreen: [
    {
      id: 'lettuce',
      nameKey: 'extraLettuce',
      name: 'Lattuga',
      price: 0,
      image: extraIngredientImages.salad,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'tomato-pachino',
      nameKey: 'extraTomatoPachino',
      name: 'Pomodoro di Pachino IGP',
      price: 0,
      image: extraIngredientImages.tomato,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'dressing',
      nameKey: 'extraDressing',
      name: 'Dressing',
      price: 0,
      image: extraIngredientImages.sauceCaesar,
      defaultCount: 1,
      maxCount: 2,
    },
  ],
  saladMixed: [
    {
      id: 'lettuce',
      nameKey: 'extraLettuce',
      name: 'Lattuga',
      price: 0,
      image: extraIngredientImages.salad,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'tomato-pachino',
      nameKey: 'extraTomatoPachino',
      name: 'Pomodoro di Pachino IGP',
      price: 0,
      image: extraIngredientImages.tomato,
      defaultCount: 1,
      maxCount: 1,
    },
    { id: 'carrot', nameKey: 'extraCarrot', name: 'Carote', price: 0, image: '🥕', defaultCount: 1, maxCount: 1 },
    { id: 'corn', nameKey: 'extraCorn', name: 'Mais', price: 0, image: '🌽', defaultCount: 1, maxCount: 1 },
    { id: 'olives', nameKey: 'extraOlives', name: 'Olive', price: 0, image: '🫒', defaultCount: 1, maxCount: 1 },
    {
      id: 'dressing',
      nameKey: 'extraDressing',
      name: 'Dressing',
      price: 0,
      image: extraIngredientImages.sauceCaesar,
      defaultCount: 1,
      maxCount: 2,
    },
  ],
  saladChickenParm: [
    {
      id: 'crispy-chicken',
      nameKey: 'extraCrispyChicken',
      name: 'Petto di pollo croccante',
      price: 0,
      image: extraIngredientImages.chickenFillet,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'tomato-pachino',
      nameKey: 'extraTomatoPachino',
      name: 'Pomodoro di Pachino IGP',
      price: 0,
      image: extraIngredientImages.tomato,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'parmesan',
      nameKey: 'extraParmesan',
      name: 'Parmigiano Reggiano DOP',
      price: 0.5,
      image: extraIngredientImages.cheese,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'lettuce',
      nameKey: 'extraLettuce',
      name: 'Lattuga',
      price: 0,
      image: extraIngredientImages.salad,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'dressing',
      nameKey: 'extraDressing',
      name: 'Dressing',
      price: 0,
      image: extraIngredientImages.sauceCaesar,
      defaultCount: 1,
      maxCount: 2,
    },
  ],
  saladChickenGrana: [
    {
      id: 'crispy-chicken',
      nameKey: 'extraCrispyChicken',
      name: 'Petto di pollo croccante',
      price: 0,
      image: extraIngredientImages.chickenFillet,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'tomato-pachino',
      nameKey: 'extraTomatoPachino',
      name: 'Pomodoro di Pachino IGP',
      price: 0,
      image: extraIngredientImages.tomato,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'grana',
      nameKey: 'extraGranaPadano',
      name: 'Grana Padano DOP',
      price: 0.5,
      image: extraIngredientImages.cheese,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'lettuce',
      nameKey: 'extraLettuce',
      name: 'Lattuga',
      price: 0,
      image: extraIngredientImages.salad,
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'dressing',
      nameKey: 'extraDressing',
      name: 'Dressing',
      price: 0,
      image: extraIngredientImages.sauceCaesar,
      defaultCount: 1,
      maxCount: 2,
    },
  ],
};

const sideExtraProfiles = {
  leRiccheBacon: [
    {
      id: 'extra-bacon',
      nameKey: 'extraSideBacon',
      name: 'Extra bacon',
      price: 0.5,
      image: extraIngredientImages.bacon,
      defaultCount: 0,
      maxCount: 2,
    },
  ],
};

const happyMealExtraProfiles = {
  happyMeal: [
    {
      id: 'apples',
      nameKey: 'extraAppleSlices',
      name: 'Fette di mela',
      price: 0,
      image: '🍎',
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'fries-kids',
      nameKey: 'extraKidsFries',
      name: 'Patatine',
      price: 0,
      image: '🍟',
      defaultCount: 0,
      maxCount: 1,
    },
    {
      id: 'water',
      nameKey: 'extraKidsWater',
      name: 'Acqua',
      price: 0,
      image: '💧',
      defaultCount: 1,
      maxCount: 1,
    },
    {
      id: 'juice',
      nameKey: 'extraKidsJuice',
      name: 'Succo di frutta',
      price: 0.5,
      image: '🧃',
      defaultCount: 0,
      maxCount: 1,
    },
  ],
};

export function getExtrasForProduct(product) {
  if (!product) return productExtras;
  if (product.type === 'salad' && product.extrasKey && saladExtraProfiles[product.extrasKey]) {
    return saladExtraProfiles[product.extrasKey];
  }
  if (product.type === 'happyMeal' && product.extrasKey && happyMealExtraProfiles[product.extrasKey]) {
    return happyMealExtraProfiles[product.extrasKey];
  }
  if (product.type === 'side' && product.extrasKey && sideExtraProfiles[product.extrasKey]) {
    return sideExtraProfiles[product.extrasKey];
  }
  return productExtras;
}

export const mealUpgradeOptions = [
  {
    id: 'meal-medium',
    name: 'Menu Medio',
    price: 3.5,
    calories: 880,
    isBestseller: true,
  },
  {
    id: 'meal-large',
    name: 'Menu Grande',
    price: 4.5,
    calories: 1120,
    showCombo: true,
  },
];

export const products = [
  /* —— Burgers —— */
  {
    id: 1,
    name: 'Big Mac',
    price: 9.49,
    image: '/products/burgers/big-mac.png',
    isBestseller: true,
    category: 'burgers',
    tags: ['beef'],
    description:
      'Due hamburger di manzo, salsa Big Mac, lattuga, formaggio, cetrioli, cipolla e panino con semi di sesamo.',
    type: 'burger',
  },
  {
    id: 116,
    name: 'Big Arch',
    price: 10.49,
    image: '/products/burgers/big-arch.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
    isBestseller: true,
  },
  {
    id: 117,
    name: 'Cheeseburger',
    price: 2.49,
    image: '/products/burgers/cheeseburger.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 118,
    name: 'Hamburger',
    price: 1.99,
    image: '/products/burgers/hamburger.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 119,
    name: 'Double Cheeseburger',
    price: 4.49,
    image: '/products/burgers/double-cheeseburger.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 120,
    name: 'Filet-O-Fish',
    price: 5.49,
    image: '/products/burgers/filet-o-fish.png',
    category: 'burgers',
    tags: ['fish'],
    type: 'burger',
  },
  {
    id: 121,
    name: 'Filet-O-Fish Deluxe',
    price: 6.49,
    image: '/products/burgers/filet-o-fish-deluxe.png',
    category: 'burgers',
    tags: ['fish'],
    type: 'burger',
  },
  {
    id: 122,
    name: 'McChicken',
    price: 5.49,
    image: '/products/burgers/mcchicken.png',
    category: 'burgers',
    tags: ['chicken'],
    type: 'burger',
  },
  {
    id: 123,
    name: 'Chickenburger',
    price: 4.99,
    image: '/products/burgers/chickenburger.png',
    category: 'burgers',
    tags: ['chicken'],
    type: 'burger',
  },
  {
    id: 124,
    name: 'McCrunchy Chicken',
    price: 7.49,
    image: '/products/burgers/mccrunchy-chicken.png',
    category: 'burgers',
    tags: ['chicken', 'mccrispy'],
    type: 'burger',
    isBestseller: true,
  },
  {
    id: 125,
    name: 'Crispy McBacon',
    price: 8.49,
    image: '/products/burgers/crispy-mcbacon.png',
    category: 'burgers',
    tags: ['beef', 'mccrispy'],
    type: 'burger',
  },
  {
    id: 126,
    name: 'Gran Crispy McBacon',
    price: 9.49,
    image: '/products/burgers/gran-crispy-mcbacon.png',
    category: 'burgers',
    tags: ['beef', 'mccrispy'],
    type: 'burger',
  },
  {
    id: 127,
    name: 'Gran Crispy McBacon Chicken',
    price: 9.99,
    image: '/products/burgers/gran-crispy-mcbacon-chicken.png',
    category: 'burgers',
    tags: ['chicken', 'mccrispy'],
    type: 'burger',
  },
  {
    id: 128,
    name: 'Gran Crispy McBacon Sweet Onion Bacon Jam',
    price: 9.99,
    image: '/products/burgers/gran-crispy-mcbacon-sweet-onion-jam.png',
    category: 'burgers',
    tags: ['beef', 'mccrispy'],
    type: 'burger',
  },
  {
    id: 129,
    name: 'Gran Crispy McBacon Chicken Sweet Onion Bacon Jam',
    price: 10.49,
    image: '/products/burgers/gran-crispy-mcbacon-chicken-sweet-onion-jam.png',
    category: 'burgers',
    tags: ['chicken', 'mccrispy'],
    type: 'burger',
    isBestseller: true,
  },
  {
    id: 130,
    name: 'Double Chicken BBQ',
    price: 8.99,
    image: '/products/burgers/double-chicken-bbq.png',
    category: 'burgers',
    tags: ['chicken'],
    type: 'burger',
  },
  {
    id: 131,
    name: 'McWrap Crispy',
    price: 7.99,
    image: '/products/burgers/mcwrap-crispy.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'wrap',
  },
  {
    id: 132,
    name: 'McWrap Crispy Chicken',
    price: 7.99,
    image: '/products/burgers/mcwrap-crispy-chicken.png',
    category: 'burgers',
    tags: ['chicken'],
    type: 'wrap',
  },
  {
    id: 133,
    name: 'McWrap Caesar Pollo Croccante',
    price: 8.49,
    image: '/products/burgers/mcwrap-caesar-pollo.png',
    category: 'burgers',
    tags: ['chicken'],
    type: 'wrap',
  },
  {
    id: 134,
    name: 'McMuffin Bacon e Uova',
    price: 4.49,
    image: '/products/burgers/mcmuffin-bacon-uova.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 135,
    name: 'Toast Prosciutto e Formaggio',
    price: 3.99,
    image: '/products/burgers/toast-prosciutto-formaggio.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
    isNew: true,
  },
  {
    id: 136,
    name: 'Colazione con Uova Strapazzate e Bacon',
    price: 6.99,
    image: '/products/burgers/colazione-uova-bacon.png',
    category: 'burgers',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 2,
    name: 'Gran Crispy McBacon Chicken Menu',
    price: 12.49,
    image: '/products/meals/gran-crispy-mcbacon-chicken-menu.png',
    isBestseller: true,
    category: 'meals',
    tags: ['chicken', 'mccrispy'],
    type: 'meal',
  },
  {
    id: 3,
    name: 'McChicken Menu',
    price: 10.49,
    image: '/products/meals/mcchicken-menu.png',
    category: 'meals',
    tags: ['chicken'],
    type: 'meal',
  },
  {
    id: 4,
    name: 'Double Cheeseburger Menu',
    price: 9.99,
    image: '/products/meals/double-cheeseburger-menu.png',
    category: 'meals',
    tags: ['beef'],
    type: 'meal',
  },
  {
    id: 5,
    name: 'Chicken McNuggets x4',
    price: 4.99,
    image: '/products/sides/mcnuggets-x4.png',
    category: 'sides',
    tags: ['nuggets', 'chicken'],
    type: 'side',
  },
  {
    id: 8,
    name: 'McCrunchy Chicken Menu',
    price: 10.99,
    image: '/products/meals/mccrunchy-chicken-menu.png',
    category: 'meals',
    tags: ['chicken', 'mccrispy'],
    type: 'meal',
  },
  {
    id: 9,
    name: 'Big Mac Menu',
    price: 11.99,
    image: '/products/meals/big-mac-menu.png',
    isBestseller: true,
    category: 'meals',
    tags: ['beef'],
    description: 'Big Mac con patatine medie e bibita a scelta.',
    type: 'meal',
  },
  {
    id: 17,
    name: 'Big Arch Menu',
    price: 12.49,
    image: '/products/meals/big-arch-menu.png',
    category: 'meals',
    tags: ['beef'],
    type: 'meal',
  },
  {
    id: 18,
    name: 'Crispy Chicken McWrap Menu',
    price: 11.49,
    image: '/products/meals/crispy-chicken-mcwrap-menu.png',
    category: 'meals',
    tags: ['chicken'],
    type: 'meal',
  },
  {
    id: 19,
    name: 'Gran Crispy McBacon Menu',
    price: 12.49,
    image: '/products/meals/gran-crispy-mcbacon-menu.png',
    category: 'meals',
    tags: ['beef', 'mccrispy'],
    type: 'meal',
  },
  {
    id: 20,
    name: 'Crispy McWrap Menu',
    price: 11.49,
    image: '/products/meals/crispy-mcwrap-menu.png',
    category: 'meals',
    tags: ['beef'],
    type: 'meal',
  },
  {
    id: 21,
    name: 'Filet-O-Fish Deluxe Menu',
    price: 10.99,
    image: '/products/meals/filet-o-fish-deluxe-menu.png',
    category: 'meals',
    tags: [],
    type: 'meal',
  },
  {
    id: 22,
    name: 'Double Chicken BBQ Menu',
    price: 11.99,
    image: '/products/meals/double-chicken-bbq-menu.png',
    isBestseller: true,
    category: 'meals',
    tags: ['chicken'],
    type: 'meal',
  },
  {
    id: 27,
    name: 'Menu Chicken McNuggets x9',
    price: 10.99,
    image: '/products/meals/chicken-mcnuggets-x9-menu.png',
    category: 'meals',
    tags: ['chicken'],
    type: 'meal',
    description: '9 Chicken McNuggets, patatine medie e bibita a scelta.',
  },
  {
    id: 28,
    name: 'Menu Spicy Chicken McNuggets x9',
    price: 11.49,
    image: '/products/meals/spicy-chicken-mcnuggets-x9-menu.png',
    isBestseller: true,
    category: 'meals',
    tags: ['chicken', 'mccrispy'],
    type: 'meal',
    description: '9 Spicy Chicken McNuggets, patatine medie e bibita a scelta.',
  },
  {
    id: 29,
    name: 'Menu Crocchette con spinaci e Parmigiano Reggiano x5',
    price: 11.49,
    image: '/products/meals/crocchette-spinaci-parmigiano-x5-menu.png',
    category: 'meals',
    tags: ['chicken'],
    type: 'meal',
    description:
      '5 crocchette con spinaci e Parmigiano Reggiano DOP, patatine medie e bibita a scelta.',
  },
  /* —— Novità —— */
  {
    id: 154,
    name: 'McShake Pompompurin® Custard',
    price: 3.99,
    image: '/products/specials/mcshake-pompompurin.png',
    category: 'new',
    tags: ['special', 'collab'],
    type: 'sweet',
    isNew: true,
    isBestseller: true,
    description: 'Shake alla crema pasticcera con topping panna e salsa al caramello.',
  },
  {
    id: 155,
    name: 'Patatine Twist Speziate',
    price: 3.99,
    image: '/products/specials/patatine-twist.png',
    category: 'new',
    tags: ['special', 'fries'],
    type: 'side',
    isNew: true,
    isBestseller: true,
    description: 'Patatine a spirale croccanti con condimento speziato.',
  },
  {
    id: 156,
    name: 'Anelli di Cipolla My Selection',
    price: 3.49,
    image: '/products/specials/anelli-cipolla.png',
    category: 'new',
    tags: ['special'],
    type: 'side',
    isNew: true,
    description: 'Anelli di cipolla croccanti e dorati.',
  },
  {
    id: 157,
    name: 'My Selection Crispy Bacon Square',
    price: 8.99,
    image: '/products/specials/my-selection-crispy-bacon.png',
    category: 'new',
    tags: ['chicken', 'mccrispy', 'special'],
    type: 'burger',
    isNew: true,
    isBestseller: true,
    description:
      'Pollo croccante, bacon, formaggio, lattuga e salsa ranch nel panino quadrato con semi di sesamo.',
  },
  /* —— Salvaeuro —— */
  {
    id: 137,
    name: 'Hamburger',
    price: 1.50,
    image: '/products/burgers/hamburger.png',
    category: 'coupons',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 138,
    name: 'Cheeseburger',
    price: 2.00,
    image: '/products/burgers/cheeseburger.png',
    category: 'coupons',
    tags: ['beef'],
    type: 'burger',
  },
  {
    id: 139,
    name: 'Chickenburger',
    price: 2.50,
    image: '/products/burgers/chickenburger.png',
    category: 'coupons',
    tags: ['chicken'],
    type: 'burger',
  },
  {
    id: 140,
    name: 'Menu Double Cheeseburger',
    price: 6.99,
    image: '/products/coupons/menu-double-cheeseburger.png',
    category: 'coupons',
    tags: ['beef', 'menu'],
    type: 'meal',
    description: 'Double Cheeseburger, patatine medie e bibita a scelta.',
  },
  {
    id: 141,
    name: 'Menu Double Chicken BBQ',
    price: 7.49,
    image: '/products/coupons/menu-double-chicken-bbq.png',
    category: 'coupons',
    tags: ['chicken', 'menu'],
    type: 'meal',
    description: 'Double Chicken BBQ, patatine medie e bibita a scelta.',
  },
  {
    id: 142,
    name: 'Menu Filet-O-Fish',
    price: 6.99,
    image: '/products/coupons/menu-filet-o-fish.png',
    category: 'coupons',
    tags: ['fish', 'menu'],
    type: 'meal',
    description: 'Filet-O-Fish, patatine medie e bibita a scelta.',
  },
  {
    id: 143,
    name: 'Caffè Espresso',
    price: 1.20,
    image: '/products/mccafe/caffe-espresso.png',
    category: 'coupons',
    tags: ['coffee'],
    type: 'sweet',
  },
  {
    id: 144,
    name: 'Milkshake Vaniglia',
    price: 2.49,
    image: '/products/sweets/milkshake-vaniglia.png',
    category: 'coupons',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 145,
    name: 'Milkshake Fragola',
    price: 2.49,
    image: '/products/sweets/milkshake-fragola.png',
    category: 'coupons',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 146,
    name: 'Milkshake Cioccolato',
    price: 2.49,
    image: '/products/sweets/milkshake-cioccolato.png',
    category: 'coupons',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 147,
    name: 'Milkshake Banana',
    price: 2.49,
    image: '/products/sweets/milkshake-banana.png',
    category: 'coupons',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 148,
    name: 'Cono',
    price: 1.50,
    image: '/products/sweets/cono.png',
    category: 'coupons',
    tags: ['gelato'],
    type: 'sweet',
  },
  {
    id: 149,
    name: 'Croissant Vuoto',
    price: 1.99,
    image: '/products/mccafe/croissant-vuoto.png',
    category: 'coupons',
    tags: ['pastry'],
    type: 'sweet',
    isNew: true,
  },
  {
    id: 150,
    name: 'Macaron Cioccolato',
    price: 2.49,
    image: '/products/mccafe/macaron-cioccolato.png',
    category: 'coupons',
    tags: ['pastry'],
    type: 'sweet',
  },
  {
    id: 151,
    name: 'McPops® al Caramello',
    price: 1.99,
    image: '/products/mccafe/mcpops-caramello.png',
    category: 'coupons',
    tags: ['mcpops'],
    type: 'sweet',
    isNew: true,
  },
  {
    id: 152,
    name: 'McPops® alla Crema',
    price: 1.99,
    image: '/products/mccafe/mcpops-crema.png',
    category: 'coupons',
    tags: ['mcpops'],
    type: 'sweet',
  },
  {
    id: 153,
    name: 'Toast Prosciutto e Formaggio',
    price: 2.49,
    image: '/products/burgers/toast-prosciutto-formaggio.png',
    category: 'coupons',
    tags: ['beef'],
    type: 'burger',
    isNew: true,
  },
  {
    id: 12,
    name: 'McPlant',
    price: 8.49,
    image: '/products/burgers/mcplant.png',
    category: 'burgers',
    tags: ['plant'],
    type: 'burger',
  },
  {
    id: 23,
    name: 'Insalata verde con Pomodoro di Pachino IGP',
    price: 7.99,
    image: '/products/salads/insalata-verde-pomodoro-pachino.png',
    category: 'salads',
    tags: ['vegetarian'],
    type: 'salad',
    extrasKey: 'saladGreen',
    description: 'Lattuga verde e pomodorini di Pachino IGP.',
  },
  {
    id: 24,
    name: 'Insalata Mista',
    price: 8.49,
    image: '/products/salads/insalata-mista.png',
    isBestseller: true,
    category: 'salads',
    tags: ['vegetarian', 'mixed'],
    type: 'salad',
    extrasKey: 'saladMixed',
    description: 'Lattuga, pomodoro, carote, mais e olive.',
  },
  {
    id: 25,
    name: 'Insalata con petto di pollo croccante, Pomodoro di Pachino IGP e Parmigiano Reggiano DOP',
    price: 10.99,
    image: '/products/salads/insalata-pollo-parmigiano.png',
    category: 'salads',
    tags: ['chicken', 'menu'],
    type: 'salad',
    extrasKey: 'saladChickenParm',
    description: 'Insalata con pollo croccante, pomodoro IGP e Parmigiano Reggiano. Include acqua.',
  },
  {
    id: 26,
    name: 'Insalata con petto di pollo croccante, Pomodoro di Pachino IGP e Grana Padano DOP',
    price: 10.99,
    image: '/products/salads/insalata-pollo-grana.png',
    isBestseller: true,
    category: 'salads',
    tags: ['chicken', 'menu'],
    type: 'salad',
    extrasKey: 'saladChickenGrana',
    description: 'Insalata con pollo croccante, pomodoro IGP e Grana Padano. Include acqua.',
  },
  {
    id: 14,
    name: 'Patatine Grandi',
    price: 3.49,
    image: '/products/sides/patatine-grandi.png',
    category: 'sides',
    tags: ['fries'],
    type: 'side',
  },
  {
    id: 44,
    name: 'Patatine Medie',
    price: 2.99,
    image: '/products/sides/patatine-medie.png',
    isBestseller: true,
    category: 'sides',
    tags: ['fries'],
    type: 'side',
  },
  {
    id: 45,
    name: 'Patate Regolari',
    price: 2.49,
    image: '/products/sides/patate-regolari.png',
    category: 'sides',
    tags: ['fries'],
    type: 'side',
  },
  {
    id: 46,
    name: 'Le Ricche Cheese & Bacon',
    price: 4.49,
    image: '/products/sides/le-ricche-cheese-bacon.png',
    category: 'sides',
    tags: ['loaded', 'fries'],
    type: 'side',
    extrasKey: 'leRiccheBacon',
  },
  {
    id: 47,
    name: 'Le Ricche Cheese & Bacon con extra bacon',
    price: 4.99,
    image: '/products/sides/le-ricche-cheese-bacon-extra.png',
    category: 'sides',
    tags: ['loaded', 'fries'],
    type: 'side',
  },
  {
    id: 48,
    name: 'Le Ricche Cheddar',
    price: 4.29,
    image: '/products/sides/le-ricche-cheddar.png',
    category: 'sides',
    tags: ['loaded', 'fries'],
    type: 'side',
  },
  {
    id: 49,
    name: 'McShaker Fries Spicy',
    price: 3.49,
    image: '/products/sides/mcshaker-fries-spicy.png',
    category: 'sides',
    tags: ['fries'],
    type: 'side',
  },
  {
    id: 50,
    name: 'Tasty Basket',
    price: 6.99,
    image: '/products/sides/tasty-basket.png',
    category: 'sides',
    tags: ['special', 'nuggets'],
    type: 'side',
    description: 'Mix di bocconcini croccanti.',
  },
  {
    id: 52,
    name: 'Spicy Chicken McNuggets x4',
    price: 5.49,
    image: '/products/sides/spicy-mcnuggets-x4.png',
    category: 'sides',
    tags: ['nuggets', 'chicken'],
    type: 'side',
  },
  {
    id: 53,
    name: 'Crocchette con spinaci e Parmigiano Reggiano x3',
    price: 3.99,
    image: '/products/sides/crocchette-spinaci-x3.png',
    category: 'sides',
    tags: ['special'],
    type: 'side',
    description: 'Prodotto con Parmigiano Reggiano DOP.',
  },
  {
    id: 54,
    name: 'Crocchette con spinaci e Parmigiano Reggiano x5',
    price: 5.49,
    image: '/products/sides/crocchette-spinaci-x5.png',
    category: 'sides',
    tags: ['special'],
    type: 'side',
    description: 'Prodotto con Parmigiano Reggiano DOP.',
  },
  {
    id: 55,
    name: 'Snack di Parmigiano Reggiano',
    price: 3.99,
    image: '/products/sides/snack-parmigiano.png',
    category: 'sides',
    tags: ['special'],
    type: 'side',
    description: 'Prodotto con Parmigiano Reggiano DOP.',
  },
  {
    id: 56,
    name: 'Ketchup',
    price: 0.5,
    image: '/products/sides/ketchup.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  {
    id: 57,
    name: 'Maionese',
    price: 0.5,
    image: '/products/sides/maionese.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  {
    id: 58,
    name: 'Salsa Senape Piccante',
    price: 0.5,
    image: '/products/sides/salsa-senape-piccante.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  {
    id: 59,
    name: 'Salsa Hot Devil',
    price: 0.5,
    image: '/products/sides/salsa-hot-devil.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  {
    id: 60,
    name: 'Salsa Barbecue',
    price: 0.5,
    image: '/products/sides/salsa-barbecue.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  {
    id: 61,
    name: 'Salsa Agrodolce',
    price: 0.5,
    image: '/products/sides/salsa-agrodolce.png',
    category: 'sides',
    tags: ['sauce'],
    type: 'sauce',
  },
  /* —— McCaffè & Desserts —— */
  {
    id: 76,
    name: 'Caffè Espresso',
    price: 1.49,
    image: '/products/mccafe/caffe-espresso.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 77,
    name: 'Caffè Americano',
    price: 1.99,
    image: '/products/mccafe/caffe-americano.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 78,
    name: 'Cappuccino',
    price: 2.49,
    image: '/products/mccafe/cappuccino.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 79,
    name: 'Cappuccino Grande',
    price: 2.99,
    image: '/products/mccafe/cappuccino-grande.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 80,
    name: 'Latte Caldo e Macchiato',
    price: 2.49,
    image: '/products/mccafe/latte-macchiato.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 103,
    name: 'Marocchino',
    price: 2.49,
    image: '/products/mccafe/marocchino.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 104,
    name: 'Caffè Ginseng',
    price: 2.29,
    image: '/products/mccafe/caffe-ginseng.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 105,
    name: 'Caffè Orzo',
    price: 2.29,
    image: '/products/mccafe/caffe-orzo.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 83,
    name: 'Cioccolata Calda',
    price: 2.49,
    image: '/products/mccafe/cioccolata-calda.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 84,
    name: 'Tè Caldo e Infusi',
    price: 2.29,
    image: '/products/mccafe/te-caldo-infusi.png',
    category: 'mcCafe',
    subcategory: 'hotCoffee',
    type: 'sweet',
  },
  {
    id: 81,
    name: 'Menu Gran Mattino',
    price: 4.99,
    image: '/products/mccafe/menu-gran-mattino.png',
    category: 'mcCafe',
    subcategory: 'mcCafeMenu',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 82,
    name: 'Menu Cappuccino',
    price: 3.99,
    image: '/products/mccafe/menu-cappuccino.png',
    category: 'mcCafe',
    subcategory: 'mcCafeMenu',
    type: 'sweet',
  },
  {
    id: 106,
    name: 'Menu Espresso',
    price: 3.49,
    image: '/products/mccafe/menu-espresso.png',
    category: 'mcCafe',
    subcategory: 'mcCafeMenu',
    type: 'sweet',
  },
  {
    id: 87,
    name: 'Croissant Vuoto',
    price: 2.29,
    image: '/products/mccafe/croissant-vuoto.png',
    category: 'mcCafe',
    subcategory: 'croissant',
    type: 'sweet',
    isNew: true,
  },
  {
    id: 107,
    name: 'Croissant alla Crema',
    price: 2.49,
    image: '/products/mccafe/croissant-alla-crema.png',
    category: 'mcCafe',
    subcategory: 'croissant',
    type: 'sweet',
    isNew: true,
  },
  {
    id: 108,
    name: "Croissant all'Albicocca",
    price: 2.49,
    image: '/products/mccafe/croissant-albicocca.png',
    category: 'mcCafe',
    subcategory: 'croissant',
    type: 'sweet',
    isNew: true,
  },
  {
    id: 109,
    name: 'Croissant Crema al Cacao e Nocciole',
    price: 2.69,
    image: '/products/mccafe/croissant-cacao-nocciole.png',
    category: 'mcCafe',
    subcategory: 'croissant',
    type: 'sweet',
    isNew: true,
  },
  {
    id: 110,
    name: 'Croissant Pistacchio',
    price: 2.69,
    image: '/products/mccafe/croissant-pistacchio.png',
    category: 'mcCafe',
    subcategory: 'croissant',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 88,
    name: 'Cheesecake Fragola',
    price: 3.49,
    image: '/products/mccafe/cheesecake-fragola.png',
    category: 'mcCafe',
    subcategory: 'cake',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 89,
    name: 'Torta Cioccolato Multistrato',
    price: 3.99,
    image: '/products/mccafe/torta-cioccolato-multistrato.png',
    category: 'mcCafe',
    subcategory: 'cake',
    type: 'sweet',
  },
  {
    id: 90,
    name: 'Donut Zucchero',
    price: 1.99,
    image: '/products/mccafe/donut-zucchero.png',
    category: 'mcCafe',
    subcategory: 'donut',
    type: 'sweet',
  },
  {
    id: 91,
    name: 'Donut Cioccolato',
    price: 2.29,
    image: '/products/mccafe/donut-cioccolato.png',
    category: 'mcCafe',
    subcategory: 'donut',
    type: 'sweet',
  },
  {
    id: 92,
    name: 'Donut Marshmallow',
    price: 2.49,
    image: '/products/mccafe/donut-marshmallow.png',
    category: 'mcCafe',
    subcategory: 'donut',
    type: 'sweet',
  },
  {
    id: 93,
    name: 'Mini Donut Zucchero',
    price: 2.49,
    image: '/products/mccafe/mini-donut-zucchero.png',
    category: 'mcCafe',
    subcategory: 'donut',
    type: 'sweet',
  },
  {
    id: 94,
    name: 'Mini Donut Cacao',
    price: 2.49,
    image: '/products/mccafe/mini-donut-cacao.png',
    category: 'mcCafe',
    subcategory: 'donut',
    type: 'sweet',
  },
  {
    id: 85,
    name: 'Muffin Cioccolato',
    price: 2.49,
    image: '/products/mccafe/muffin-cioccolato.png',
    category: 'mcCafe',
    subcategory: 'muffin',
    type: 'sweet',
  },
  {
    id: 86,
    name: 'Muffin con Nutella®',
    price: 2.69,
    image: '/products/mccafe/muffin-nutella.png',
    category: 'mcCafe',
    subcategory: 'muffin',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 95,
    name: 'Macaron Cioccolato',
    price: 2.99,
    image: '/products/mccafe/macaron-cioccolato.png',
    category: 'mcCafe',
    subcategory: 'macaron',
    type: 'sweet',
  },
  {
    id: 96,
    name: 'Macaron Lampone',
    price: 2.99,
    image: '/products/mccafe/macaron-lampone.png',
    category: 'mcCafe',
    subcategory: 'macaron',
    type: 'sweet',
  },
  {
    id: 97,
    name: 'Macaron Pistacchio',
    price: 2.99,
    image: '/products/mccafe/macaron-pistacchio.png',
    category: 'mcCafe',
    subcategory: 'macaron',
    type: 'sweet',
  },
  {
    id: 98,
    name: 'Tiramisù',
    price: 3.49,
    image: '/products/mccafe/tiramisu.png',
    category: 'mcCafe',
    subcategory: 'cake',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 99,
    name: 'Pancake con Sciroppo',
    price: 3.99,
    image: '/products/mccafe/pancake-sciroppo.png',
    category: 'mcCafe',
    subcategory: 'mcCafeMenu',
    type: 'sweet',
  },
  {
    id: 100,
    name: 'Actimel Fragola',
    price: 1.99,
    image: '/products/mccafe/actimel-fragola.png',
    category: 'mcCafe',
    subcategory: 'juice',
    type: 'sweet',
  },
  {
    id: 111,
    name: 'GelaTino',
    price: 3.49,
    image: '/products/mccafe/gelatino.png',
    category: 'mcCafe',
    subcategory: 'fresh',
    type: 'sweet',
  },
  {
    id: 112,
    name: 'Crema al Caffè',
    price: 2.99,
    image: '/products/mccafe/crema-al-caffe.png',
    category: 'mcCafe',
    subcategory: 'fresh',
    type: 'sweet',
  },
  {
    id: 113,
    name: 'Spremuta d\'Arancia',
    price: 2.99,
    image: '/products/mccafe/spremuta-arancia.png',
    category: 'mcCafe',
    subcategory: 'juice',
    type: 'sweet',
    isBestseller: true,
  },
  {
    id: 114,
    name: 'Succo di Frutta Pesca',
    price: 2.49,
    image: '/products/mccafe/succo-pesca.png',
    category: 'mcCafe',
    subcategory: 'juice',
    type: 'sweet',
    description: 'Senza zuccheri aggiunti.',
  },
  {
    id: 115,
    name: 'Succo di Frutta Pera',
    price: 2.49,
    image: '/products/mccafe/succo-pera.png',
    category: 'mcCafe',
    subcategory: 'juice',
    type: 'sweet',
    description: 'Senza zuccheri aggiunti.',
  },
  {
    id: 101,
    name: 'McPops® al Caramello',
    price: 2.49,
    image: '/products/mccafe/mcpops-caramello.png',
    category: 'mcCafe',
    subcategory: 'mcpops',
    type: 'sweet',
    isNew: true,
  },
  {
    id: 102,
    name: 'McPops® alla Crema',
    price: 2.49,
    image: '/products/mccafe/mcpops-crema.png',
    category: 'mcCafe',
    subcategory: 'mcpops',
    type: 'sweet',
  },
  {
    id: 15,
    name: 'McFlurry Oreo',
    price: 4.49,
    image: '/products/sweets/mcflurry-oreo.png',
    isBestseller: true,
    category: 'sweets',
    tags: ['mcflurry'],
    type: 'sweet',
  },
  {
    id: 62,
    name: 'Milkshake Vaniglia',
    price: 3.99,
    image: '/products/sweets/milkshake-vaniglia.png',
    category: 'sweets',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 63,
    name: 'Milkshake Fragola',
    price: 3.99,
    image: '/products/sweets/milkshake-fragola.png',
    category: 'sweets',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 64,
    name: 'Milkshake Cioccolato',
    price: 3.99,
    image: '/products/sweets/milkshake-cioccolato.png',
    category: 'sweets',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 65,
    name: 'Milkshake Banana',
    price: 3.99,
    image: '/products/sweets/milkshake-banana.png',
    category: 'sweets',
    tags: ['milkshake'],
    type: 'sweet',
  },
  {
    id: 66,
    name: 'McFlurry Snickers',
    price: 4.99,
    image: '/products/sweets/mcflurry-snickers.png',
    category: 'sweets',
    tags: ['mcflurry'],
    type: 'sweet',
  },
  {
    id: 67,
    name: 'McFlurry gusto Dubai Chocolate Style',
    price: 5.49,
    image: '/products/sweets/mcflurry-dubai-chocolate.png',
    category: 'sweets',
    tags: ['mcflurry'],
    type: 'sweet',
  },
  {
    id: 68,
    name: 'McFlurry Baci Perugina',
    price: 4.99,
    image: '/products/sweets/mcflurry-baci.png',
    category: 'sweets',
    tags: ['mcflurry'],
    type: 'sweet',
  },
  {
    id: 69,
    name: 'Cono',
    price: 1.99,
    image: '/products/sweets/cono.png',
    category: 'sweets',
    tags: ['gelato'],
    type: 'sweet',
  },
  {
    id: 70,
    name: 'Sundae Fiordilatte',
    price: 2.49,
    image: '/products/sweets/sundae-fiordilatte.png',
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
  },
  {
    id: 71,
    name: 'Sundae Cioccolato',
    price: 2.49,
    image: '/products/sweets/sundae-cioccolato.png',
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
  },
  {
    id: 72,
    name: 'Sundae Caramello',
    price: 2.49,
    image: '/products/sweets/sundae-caramello.png',
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
  },
  {
    id: 73,
    name: 'Sundae Caffè',
    price: 2.49,
    image: '/products/sweets/sundae-caffe.png',
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
  },
  {
    id: 74,
    name: 'Sundae Frutti di Bosco',
    price: 2.49,
    image: '/products/sweets/sundae-frutti-bosco.png',
    isBestseller: true,
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
    description: 'Nuova ricetta.',
  },
  {
    id: 75,
    name: 'Sundae Baci Perugina',
    price: 2.99,
    image: '/products/sweets/sundae-baci.png',
    category: 'sweets',
    tags: ['sundae'],
    type: 'sweet',
  },
  {
    id: 16,
    name: 'Coca-Cola',
    price: 2.99,
    image: '/products/drinks/coca-cola.png',
    isBestseller: true,
    category: 'drinks',
    tags: ['soft'],
    type: 'drink',
  },
  {
    id: 30,
    name: 'Coca-Cola Zero Zuccheri',
    price: 2.99,
    image: '/products/drinks/coca-cola-zero.png',
    category: 'drinks',
    tags: ['soft'],
    type: 'drink',
  },
  {
    id: 31,
    name: 'Fanta',
    price: 2.99,
    image: '/products/drinks/fanta.png',
    category: 'drinks',
    tags: ['soft'],
    type: 'drink',
  },
  {
    id: 32,
    name: 'Sprite Zero Zucchero',
    price: 2.99,
    image: '/products/drinks/sprite-zero.png',
    category: 'drinks',
    tags: ['soft'],
    type: 'drink',
  },
  {
    id: 33,
    name: 'Acqua San Benedetto Naturale',
    price: 1.99,
    image: '/products/drinks/acqua-san-benedetto-naturale.png',
    category: 'drinks',
    tags: ['water'],
    type: 'drink',
  },
  {
    id: 34,
    name: 'Acqua San Benedetto Bolle Decise',
    price: 1.99,
    image: '/products/drinks/acqua-san-benedetto-frizzante.png',
    category: 'drinks',
    tags: ['water'],
    type: 'drink',
  },
  {
    id: 35,
    name: 'Lipton Ice Tea Pesca Zero',
    price: 2.49,
    image: '/products/drinks/lipton-pesca-zero.png',
    category: 'drinks',
    tags: ['tea'],
    type: 'drink',
  },
  {
    id: 36,
    name: 'Lipton Ice Tea Limone Zero',
    price: 2.49,
    image: '/products/drinks/lipton-limone-zero.png',
    category: 'drinks',
    tags: ['tea'],
    type: 'drink',
  },
  {
    id: 37,
    name: 'Tropicana Pressed Orange',
    price: 2.99,
    image: '/products/drinks/tropicana-arancia.png',
    category: 'drinks',
    tags: ['juice'],
    type: 'drink',
  },
  {
    id: 38,
    name: "Frullà Drink Succo di Mela",
    price: 2.49,
    image: '/products/drinks/frulla-succo-mela-bio.png',
    category: 'drinks',
    tags: ['juice'],
    type: 'drink',
    description: 'Succo di mela con mele italiane biologiche.',
  },
  {
    id: 39,
    name: "Leni's Succo di Mela",
    price: 2.49,
    image: '/products/drinks/lenis-succo-mela.png',
    category: 'drinks',
    tags: ['juice'],
    type: 'drink',
    description: '100% mela italiana.',
  },
  {
    id: 40,
    name: 'Happy Meal Hamburger',
    price: 5.99,
    image: '/products/happy-meals/happy-meal-hamburger.png',
    category: 'happyMeals',
    tags: ['beef'],
    type: 'happyMeal',
    extrasKey: 'happyMeal',
    description: 'Hamburger, fette di mela e acqua.',
  },
  {
    id: 41,
    name: 'Happy Meal Chickenburger',
    price: 5.99,
    image: '/products/happy-meals/happy-meal-chickenburger.png',
    isBestseller: true,
    category: 'happyMeals',
    tags: ['chicken'],
    type: 'happyMeal',
    extrasKey: 'happyMeal',
    description: 'Chickenburger, fette di mela e acqua.',
  },
  {
    id: 42,
    name: 'Happy Meal McNuggets',
    price: 5.99,
    image: '/products/happy-meals/happy-meal-mcnuggets.png',
    category: 'happyMeals',
    tags: ['chicken', 'nuggets'],
    type: 'happyMeal',
    extrasKey: 'happyMeal',
    description: '4 Chicken McNuggets, fette di mela e acqua.',
  },
  {
    id: 43,
    name: 'Happy Meal Toast',
    price: 5.99,
    image: '/products/happy-meals/happy-meal-toast.png',
    category: 'happyMeals',
    tags: ['toast'],
    type: 'happyMeal',
    extrasKey: 'happyMeal',
    description: 'Toast con formaggio e prosciutto, fette di mela e acqua.',
  },
];

export const productExtras = [
  {
    id: 'cheese',
    name: 'Formaggio',
    price: 0,
    image: extraIngredientImages.cheese,
    defaultCount: 1,
    maxCount: 3,
  },
  {
    id: 'bacon',
    name: 'Bacon',
    price: 0.5,
    image: extraIngredientImages.bacon,
    defaultCount: 0,
    maxCount: 2,
  },
  {
    id: 'tomato',
    name: 'Pomodoro',
    price: 0,
    image: extraIngredientImages.tomato,
    defaultCount: 1,
    maxCount: 3,
  },
  {
    id: 'onion',
    name: 'Cipolla',
    price: 0,
    image: extraIngredientImages.onion,
    defaultCount: 1,
    maxCount: 3,
  },
  {
    id: 'sauce',
    name: 'Salsa Big Mac',
    price: 0,
    image: extraIngredientImages.sauceBigMac,
    defaultCount: 1,
    maxCount: 2,
  },
];

/**
 * Modalità ordinamento cross-sell (scheda prodotto).
 * `random` oggi; in futuro `popular` + popularRanking da app gestionale.
 */
export const crossSellSortMode = 'random';

export const crossSellItems = [
  {
    id: 'cola',
    name: 'Coca-Cola',
    price: 2.99,
    image: '/products/drinks/coca-cola.png',
    isBestseller: true,
    productId: 16,
  },
  {
    id: 'cola-zero',
    name: 'Coca-Cola Zero Zuccheri',
    price: 2.99,
    image: '/products/drinks/coca-cola-zero.png',
    productId: 30,
  },
  {
    id: 'fanta',
    name: 'Fanta',
    price: 2.99,
    image: '/products/drinks/fanta.png',
    productId: 31,
  },
  {
    id: 'sprite-zero',
    name: 'Sprite Zero Zucchero',
    price: 2.99,
    image: '/products/drinks/sprite-zero.png',
    productId: 32,
  },
  {
    id: 'acqua-naturale',
    name: 'Acqua San Benedetto Naturale',
    price: 1.99,
    image: '/products/drinks/acqua-san-benedetto-naturale.png',
    productId: 33,
  },
  {
    id: 'lipton-pesca',
    name: 'Lipton Ice Tea Pesca Zero',
    price: 2.49,
    image: '/products/drinks/lipton-pesca-zero.png',
    productId: 35,
  },
  {
    id: 'fries',
    name: 'Patatine Medie',
    price: 2.99,
    image: '/products/sides/patatine-medie.png',
    isBestseller: true,
    productId: 44,
  },
  {
    id: 'fries-large',
    name: 'Patatine Grandi',
    price: 3.49,
    image: '/products/sides/patatine-grandi.png',
    productId: 14,
  },
  {
    id: 'mcshaker',
    name: 'McShaker Fries Spicy',
    price: 3.49,
    image: '/products/sides/mcshaker-fries-spicy.png',
    productId: 49,
  },
  {
    id: 'mcnuggets',
    name: 'Chicken McNuggets x4',
    price: 4.99,
    image: '/products/sides/mcnuggets-x4.png',
    productId: 5,
  },
  {
    id: 'le-ricche',
    name: 'Le Ricche Cheese & Bacon',
    price: 4.49,
    image: '/products/sides/le-ricche-cheese-bacon.png',
    productId: 46,
  },
  {
    id: 'crocchette',
    name: 'Crocchette spinaci e Parmigiano x3',
    price: 3.99,
    image: '/products/sides/crocchette-spinaci-x3.png',
    productId: 53,
  },
  {
    id: 'mcflurry',
    name: 'McFlurry Oreo',
    price: 4.49,
    image: '/products/sweets/mcflurry-oreo.png',
    productId: 15,
  },
  {
    id: 'milkshake-vanilla',
    name: 'Milkshake Vaniglia',
    price: 3.99,
    image: '/products/sweets/milkshake-vaniglia.png',
    productId: 62,
  },
];
